server:
  port: 8080

spring:
  application:
    name: "accounts"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/walrus
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  config:
    import:
      - "application_prod.yaml"

  profiles:
    active:
      - "prod"

build:
  version: "2.0"

accounts:
  message: "Welcome to walrus accounts"
  contactDetails:
    name: "Walrus Svenson"
    email: "walrus@osada.cz"
  callSupport:
    - 666420690
    - 420696666

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-sate:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    version: "1.0.0"


resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      permitted-number-of-calls-in-half-open-state: 2
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10000
